# This installs and starts/restarts all Docker applications.
---

- name: Install Hetzner Docker Apps
  hosts: hetzner
  remote_user: apprun
  vars:
    force_pull: false
    stop_container: true
  roles:
    - role: docker_cron
      tags: cron
    - role: docker_nginx
      tags: nginx
    - role: docker_tandoor
      tags: tandoor
    - role: docker_anki
      tags: anki
    - role: docker_firefly
      tags: firefly
    - role: docker_minecraft
      tags: minecraft
    - role: docker_photo
      tags: photo
    - role: docker_jelly
      tags: jelly
    - role: docker_nextcloud
      tags: nextcloud
    - role: docker_chore_planner
      tags: chore_planner
    - role: docker_forgejo
      tags: forgejo

- name: Install Raspberry Docker Apps
  hosts: raspberry
  remote_user: apprun
  vars:
    force_pull: false
    stop_container: true
  roles:
    - role: docker_nginx
      tags: nginx
    - role: docker_node_red
      tags: node_red
