---

- name: Create Docker Forgejo Directory
  ansible.builtin.file:
    dest: "{{ docker_forgejo_dir }}"
    state: directory
    mode: "0755"
  notify: docker_forgejo_restart

- name: Create Docker Forgejo Box Directory
  ansible.builtin.file:
    dest: "{{ docker_forgejo_box_dir }}"
    state: directory
    mode: "0755"
  notify: docker_forgejo_restart

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_forgejo_dir }}/docker-compose.yml"
    mode: "0644"
  notify: docker_forgejo_restart

- name: Force Pull
  ansible.builtin.command: "true"
  changed_when: force_pull
  notify: docker_forgejo_restart

- name: Force Stop Container
  ansible.builtin.command: "true"
  changed_when: stop_container
  notify: docker_forgejo_down
